stages:
  preprocess_train:
    cmd: python src\preprocess_data.py -s 1 -i data/raw/1_2024-05-07-21-21-39.csv data/raw/2_2024-05-07-21-29-59.csv data/raw/3_2024-05-07-21-39-27.csv
  preprocess_test:
    cmd: python src\preprocess_data.py -s 0 -i data/raw/1_2024-05-07-21-21-39.csv data/raw/2_2024-05-07-21-29-59.csv
  train_model:
    cmd: python src\train_model.py -m models/lin_reg_v1.joblib
  test_model:
    cmd: python src\test_model.py -m models/lin_reg_v1.joblib
